### ISSUE TITLE
title aligned to right

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Flat-Boat#4]
@rodica-andronache @DragosBubu tema asta+ child lawyeria au ajuns live pe repo si cred ca mai sunt probleme mici, de ex aici vad ca tilurile + data sunt aliniate la dreapta si se vede super ciudat.

Asa a fost intentia ?

**Comment by DragosBubu** [comment]
@ineagu Am vrut sa fie diferit de parinte.

**Comment by ineagu** [comment]
ah ok, am crezut ca e un bug :) mi se pare putin ciudat
